# Generated by Django 4.0.3 on 2022-05-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuahang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cua_hang', models.CharField(max_length=200)),
                ('ma_cua_hang', models.CharField(max_length=200)),
                ('dia_chi', models.CharField(max_length=200)),
                ('ngay_tao', models.DateTimeField(verbose_name='publish date')),
            ],
        ),
    ]
