# Generated by Django 4.0.3 on 2022-05-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='san_pham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=200)),
                ('ma_san_pham', models.CharField(max_length=200)),
            ],
        ),
    ]
